broker:
  name: Bot Santiago
  login: 5040181463
  password: "YrFx@k2c"
  server: "MetaQuotes-Demo"

broker_EURUSD:
  name: Bot Lorenzo
  login: 5040184369
  password: "YrFx@k2c"
  server: "MetaQuotes-Demo"

trading:
  symbol: "EURUSD"
  timeframe: "15m"
  capital: 1000
  risk_per_trade: 0.03
