broker:
  name: Bot Santiago
  login: 5040181463
  password: "YrFx@k2c"
  server: "MetaQuotes-Demo"



trading:
  symbol: "EURUSD"
  timeframe: "15m"     # '1d', '1h', '15m', etc.
  capital: 1000
  risk_per_trade: 0.03
